# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dbe62315ce4faf8f2037a98e55d5a41694c3be3b99da57d9d330ca937fb77f8adcb39b5016b8318f59a616618d2916cbdd77e04c9b6ad139a4379a26814c2ca

test:
  secret_key_base: c668d2033179309c1cf70f2ba893e8c3eceebc0e1a6c2d9db4127f3440894bc0fc30018c198d7731233f3c6250999526f680e780cf7aa8ba3b79c028d1b2202c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
